site_name: test_Packaging_readthedocs

nav:
  - Home: index.md
  - API: 
    - solvers: modules/solvers.md
    - utils: modules/utils.md
    - pinn: modules/pinn.md

theme: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

