site_name: Mklorum

nav:
  - Home: index.md
  - About: about.md

theme: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

